#alias ls='ls -dF'
alias l='ls -rltF'
alias c='clear'
alias x='exit'
alias h='history'

alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'

alias cdg='cd ~/git_products/'
alias cdga='cd ~/git_products/app/'
alias cdgl='cd ~/git_products/lib/'
alias cdgc='cd ~/git_products/script/'
alias cdgt='cd ~/git_products/tool/'
